name: Build

on: [pull_request]

jobs:
  ubuntu-build:
    name: Debian Travis CI build
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile
        run: |
          export TRAVIS_DEBIAN_GIT_BUILDPACKAGE_OPTIONS=---git-ignore-new
          export TRAVIS_DEBIAN_TARGET_DIR="$PWD"
          sh ci/build.sh
