name: Build

on: [push, pull_request]

jobs:
  ubuntu-build:
    name: Ubuntu CI build
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Compile
        run: sh ci/script.sh
